### ISSUE TITLE
More capacity from Rackspace

### ISSUE THREAD

**Issue by kenperkins** [iojs/build#46]
I know @pquerna has facilitated some of this directly, but my team (Developer Experience) has an official program for capacity for OSS projects, for ci/cd, web, builds, etc. 

Let me know if I can help with this in any way...

**Comment by bnoordhuis** [comment]
That's a really nice gesture, thanks!  My two cents: anything that would speed up the CI would be great because building the project and running the test suite can be pretty agonizing now.  Something that would be able to run the benchmarks reliably after each commit would be pretty awesome as well.

That said, @rvagg should really be the one to comment, he has the most insight into the CI infrastructure.

**Comment by rmg** [comment]
Rackspace has "bare-metal" servers. That could be very useful for benchmarking.

**Comment by kenperkins** [comment]
For context, they're fully [on-demand bare-metal servers](http://www.rackspace.com/cloud/servers/onmetal) with the same CRUD API as all of our cloud servers, available through [`pkgcloud`](https://www.npmjs.org/package/pkgcloud)

**Comment by kenperkins** [comment]
This is not actionable, and I'm now part of the committee (representing Rackspace), so we can deal with it as appropriate moving forward. As such, I'm going to close this issue.
