### ISSUE TITLE
use Ansible Vault to store website crt and key files

### ISSUE THREAD

**Issue by kenperkins** [iojs/build#50]
Instead of having these in `.gitignore` and required to be on a local machine to deploy, how about we store these in [Ansible Vault](http://docs.ansible.com/playbooks_vault.html)?

Example:

```yaml
ssl_certificate: |
  -----BEGIN CERTIFICATE-----
  blahblahblah
  -----END CERTIFICATE-----

ssl_certificate_key: |
  -----BEGIN RSA PRIVATE KEY-----
  blahblahblah
  -----END RSA PRIVATE KEY-----
```

**Comment by rmg** [comment]
How does this model stand up to attacks over time? Because it gets stored in git you basically lose the ability to change the encryption key as a means of extending the shelf life of the secrecy. In other words, once you go down this path, the first password/key you use has to be strong enough to last "forever" (as long as secrecy is needed).

I think this model might only be suitable for private repos, where you have at least some control over who gets to try to break your keys.

**Comment by kenperkins** [comment]
These are good questions. We already have an invalidation problem for sensitive data should someone leave the project. 

We also know that some of the values here are time-boxed; for example we'll probably have new certs every year or two.

That said you may be right; I'm doing some further digging.

**Comment by kenperkins** [comment]
https://groups.google.com/forum/#!msg/ansible-project/iu4ISgHStTY/sDA4o6YimEQJ

And then a [commit](https://github.com/ansible/ansible/commit/2d478b16279fa2d6eda1c8ebd5a1881b4172f69c#diff-df4c9760154e1be8d4a92830ff61b2bf) to Ansible that appears to add a `AES256` and `PBKDF2`.

Still trying to digg more.

**Comment by kenperkins** [comment]
I feel like absent a more open security review from a known expert, I'm in agreement that this isn't worth the risk right now.

**Comment by rmg** [comment]
I agree with the goal of a consolidating these things, though. Thanks for taking a stab at it!
